### ISSUE TITLE
pre-whitening wizard not working

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-resmap#3]
Am I using wrong parameter values?

```
INFO Entered into dir: cd '/beegfs2/gsharov/ScipionUserData/projects/relion30_tutorial_scipion'
== BEGIN Resolution Map Calculation == 

= Reading Input Parameters
  :: Time elapsed: 0 minutes and 0.19 seconds


= Testing Whether the Input Volume has been Low-pass Filtered

=======================================================================
|                                                                     |
|          The input volume is quite large ( >160 voxels).            |
|                                                                     |
|         ResMap will run its low-pass filtering test on a            |
|       cube of size 160 taken from the center of the volume.         |
|                                                                     |
|        This is usually not a problem, but please notify the         |
|                  authors if something goes awry.                    |
|                                                                     |
=======================================================================

=======================================================================
|                                                                     |
|        The volume does not appear to be low-pass filtered.          |
|                                                                     |
|                              Great!                                 |
|                                                                     |
=======================================================================

  :: Time elapsed: 0 minutes and 1.82 seconds


= ResMap will now run with the following parameters
  inputMap:     volume1.map
  vxSize:       0.89
  pValue:       0.05
  minRes:       10.00
  maxRes:       3.50
  stepRes:      1.00
  LPFfactor:    0.00

= Computing Mask Separating Particle from Background
  :: Time elapsed: 0 minutes and 3.57 seconds

=======================================================================
|                                                                     |
|                 ResMap Pre-Whitening (beta) Tool                    |
|                                                                     |
|                    The volume is quite large.                       |
|                                                                     |
|          ResMap will run its pre-whitening on the largest           |
|     cube it can fit within the particle and in the background.      |
|                                                                     |
|          In split volume mode, ResMap will only fit a cube          |
|  inside the particle and use the difference map as the background.  |
|                                                                     |
=======================================================================


= Computing The Largest Cube Within the Particle
  :: Time elapsed: 0 minutes and 0.33 seconds

= Computing The Largest Cube in the Background
  :: Time elapsed: 0 minutes and 0.46 seconds

= Extracting Cubes and Calculating Spherically Averaged Power Spectra
Exception in Tkinter callback
Traceback (most recent call last):
  File "/lmb/home/gsharov/soft/scipion2/software/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/lmb/home/gsharov/soft/scipion2/software/lib/python2.7/lib-tk/Tkinter.py", line 592, in callit
    func(*args)
  File "/lmb/home/gsharov/soft/scipion2/pyworkflow/gui/dialog.py", line 631, in proccess
    func()
  File "/lmb/home/gsharov/soft/scipion-em-plugins/scipion-em-resmap/resmap/wizards.py", line 184, in _runBeforePreWhitening
    self.results = prot.runResmap(self.workingDir, wizardMode=True)
  File "/lmb/home/gsharov/soft/scipion-em-plugins/scipion-em-resmap/resmap/protocols/protocol_resmap.py", line 296, in runResmap
    results = ResMap_algorithm(**args)
  File "/lmb/home/gsharov/soft/scipion2/software/em/resmap-1.1.5-s2/ResMap_algorithm.py", line 229, in ResMap_algorithm
    scipionPrewhitenParams = scipionPrewhitenParams
  File "/lmb/home/gsharov/soft/scipion2/software/em/resmap-1.1.5-s2/ResMap_algorithm.py", line 860, in preWhiteningLoop
    insideBox[2]-halfWidthBox:insideBox[2]+halfWidthBox ];
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by azazellochg** [comment]
not relevant anymore.
